name: CI
on: [push]
jobs:
  python38-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Apt install
        run: cat Aptfile | sudo xargs apt-get install

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - id: cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Poetry install
        run: pip install -Iv Poetry==1.7.0

      - name: Install dependencies
        run: poetry install -v

      - name: Tests
        run: poetry run pytest

      - name: Linting
        run: |
          poetry run pylint mitxpro_core/
          poetry run black --check .
          poetry run isort -c
